apiVersion: apps/v1
kind: Deployment
metadata:
  name: gettasks-todo-microservice
  labels:
    app: gettasks-todo-microservice
spec:
   replicas: 2
   selector:
     matchLabels:
        app: gettasks-todo-microservice
   template:
     metadata:
       labels:
          app: gettasks-todo-microservice
     spec:
       containers:
          - name: gettasks-todo-microservice-pod
            image: k8acrregistry.azurecr.io/gettaskstodo:latest
            ports:
              - containerPort: 8000
            env:
              - name: CONNECTION_STRING
                value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:k8sqlserverc.database.windows.net,1433;Database=k8db;Uid=sqladmin;Pwd=Password@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"                                          
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "250m"
                memory: "256Mi"