{{- if .Values.createIstioResources }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-microtodo-virtualservice
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - istio-system/microtodo-gateway
  http:
  - match:
    - uri:
        prefix: "/api/gettasks"
    route:
    - destination:
        host: {{ .Release.Name }}-gettasks-todo-microservice-service
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/addtasks"
    route:
    - destination:
        host: {{ .Release.Name }}-addtask-todo-microservice-service
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api/deletetasks"
    route:
    - destination:
        host: {{ .Release.Name }}-deletetask-todo-microservice-service
        port:
          number: 80
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ .Release.Name }}-microtodo-ui-service
        subset: blue
        port:
          number: 80
      weight: 100
    - destination:
        host: {{ .Release.Name }}-microtodo-ui-service
        subset: green
        port:
          number: 80
      weight: 0
{{- end }}