{{- if .Values.createIstioResources }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-microtodo-virtualservice
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - istio-system/{{ .Release.Name }}-microtodo-gateway
  http:

   # INIT: Call "/" of backend to create DB table
  - match:
      - uri:
          exact: "/api/init"
    rewrite:
      uri: "/"
    route:
      - destination:
          host: {{ .Release.Name }}-gettasks-todo-microservice-service
          port:
            number: 80
  
  # GET TASKS — /api/tasks
  - match:
      - uri:
          exact: "/api/tasks"
        method:
          exact: "GET"
    rewrite:
      uri: "/tasks"
    route:
      - destination:
          host: {{ .Release.Name }}-gettasks-todo-microservice-service
          port:
            number: 80

  # CREATE TASK — POST /api/tasks
  - match:
      - uri:
          exact: "/api/tasks"
        method:
          exact: "POST"
    rewrite:
      uri: "/tasks"
    route:
      - destination:
          host: {{ .Release.Name }}-addtask-todo-microservice-service
          port:
            number: 80

  # DELETE TASK — /api/tasks/{id}
  - match:
      - uri:
          prefix: "/api/tasks/"
        method:
          exact: "DELETE"
    rewrite:
      uri: "/tasks/"
    route:
      - destination:
          host: {{ .Release.Name }}-deletetask-todo-microservice-service
          port:
            number: 80

    # UI fallback
  - match:
      - uri:
          prefix: "/"
    route:
      - destination:
          host: {{ .Release.Name }}-microtodo-ui-service
          subset: blue
          port:
            number: 80
        weight: 90
      - destination:
          host: {{ .Release.Name }}-microtodo-ui-service
          subset: green
          port:
            number: 80
        weight: 10

{{- end }}
