resource_group_name = "devrg-k8s-infra"
location            = "Central India"
acr_name            = "k8acrregistrydev"
sql_server_name     = "devk8sqlserverc"
database_name       = "devk8db"
k8_name             = "devtodo-aks-cluster"
key_vault_name      = "devtodo-kv"
kv_secret_name = "SqlAdminPasswordNew"